### ISSUE TITLE
MIUI11 android8.0下大概率闪退，用户无法升级webview日志

### ISSUE THREAD

**Issue by hao86** [lazy-luo/smarGate#4]
**Describe the bug**
MIUI11 android8.0下大概率闪退，用户无法升级webview

**To Reproduce**
1. 自动登录后闪退日志如下：
2019-10-14 21:57:12App Version: 1.01_1OS Version: 8.0.0_26Vendor: XiaomiModel: MI 5s PlusCPU ABI: arm64-v8aarmeabi-v7aarmeabijava.util.IllegalFormatConversionException: f != java.lang.Integerat java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4402)at java.util.Formatter$FormatSpecifier.printFloat(Formatter.java:2897)at java.util.Formatter$FormatSpecifier.print(Formatter.java:2844)at java.util.Formatter.format(Formatter.java:2523)at java.util.Formatter.format(Formatter.java:2458)at java.lang.String.format(String.java:2770)at com.smarGate.MainActivity.setStatus(MainActivity.java:774)at com.smarGate.MyTimeTask.run(MainActivity.java:59)at java.util.TimerThread.mainLoop(Timer.java:555)at java.util.TimerThread.run(Timer.java:505)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lazy-luo** [comment]
此为BUG，已在网盘链接中修复：https://pan.baidu.com/s/14Iq60kxHW711NVoCVKWySg
已同步到github，主要是显示cpu使用率时出现格式转换问题，BUG产生于0.22版本。

**Comment by hao86** [comment]
> 此为BUG，已在网盘链接中修复：https://pan.baidu.com/s/14Iq60kxHW711NVoCVKWySg
> 已同步到github，主要是显示cpu使用率时出现格式转换问题，BUG产生于0.22版本。

网盘的版本也是一样的问题，问题没有解决

**Comment by lazy-luo** [comment]
crash日志完全一样？关键是这行：com.smarGate.MainActivity.setStatus(MainActivity.java:774)at

**Comment by lazy-luo** [comment]
> > 此为BUG，已在网盘链接中修复：https://pan.baidu.com/s/14Iq60kxHW711NVoCVKWySg
> > 已同步到github，主要是显示cpu使用率时出现格式转换问题，BUG产生于0.22版本。
> 
> 网盘的版本也是一样的问题，问题没有解决

其它型号手机未见此问题。重新修复了一下此BUG，由于没有真机环境，请从网盘链接重新下载覆盖安装。如果任然crash，请贴出日志；如已修复请跟帖确认。

**Comment by hao86** [comment]
> crash日志完全一样？关键是这行：com.smarGate.MainActivity.setStatus(MainActivity.java:774)at

安装之后第一次打开还是报错，但是到目前为止没报错了，抱歉！

**Comment by lazy-luo** [comment]
> > crash日志完全一样？关键是这行：com.smarGate.MainActivity.setStatus(MainActivity.java:774)at
> 
> 安装之后第一次打开还是报错，但是到目前为止没报错了，抱歉！

安装之后第一次打开如果之只是显示错误信息，则是正常的，那是之前版本的crash日志。后续如继续crash请继续在本issue跟帖。

**Comment by TrueRux** [comment]
MIUI10 注册失败，显示“注册失败，请确认信息填写无误”

**Comment by lazy-luo** [comment]
@TrueRux 请仔细看说明：注册时不能填中文。

**Comment by TrueRux** [comment]
> 
> 
> @TrueRux 请仔细看说明：注册时不能填中文。

谢谢
